### ISSUE TITLE
ilu0 returns wrong results for sparse matrix solve

### ISSUE THREAD

**Issue by simon-lc** [mcovalt/ILUZero.jl#10]
Thanks for the great package, this is a very useful tool!

I am having issues using the factorization for some matrices. I tried using the `ilu0` factorization on a small matrix 10x10 with good condition number.  The result is very different from what I obtain with the base `\` operator. I have attached an example below:

```
using Random
Random.seed!(0)

n = 10
B = sprand(n,n,1.0) # works
B = sprand(n,n,0.9) # doesn't work
cond(Matrix(B))
lu_factorization = ilu0(B)
x0 = zeros(n)
r = rand(n)
ldiv!(x0, lu_factorization, r)
norm(B * x0 - r, Inf)
x1 = B \ r
norm(B * x1 - r, Inf)
norm(x0 - x1, Inf)
```

Interestingly when all the entries in the matrix are filled the results is correct. 
I am not sure if I am missing something here, can you help me sort this issue out?

Thanks for your help!
Simon

**Comment by mcovalt** [comment]
Thanks for reporting this! This is actually the behavior we'd expect.

From [Wikipedia](https://en.wikipedia.org/wiki/Incomplete_LU_factorization) (emphasis mine):
> An incomplete factorization instead seeks triangular matrices $L$, $U$ such that $A\approx LU$ rather than $A=LU$. **Solving for $LUx=b$ can be done quickly but does not yield the exact solution to $Ax=b$**. So, we instead use the matrix $M=LU$ as a preconditioner in another iterative solution algorithm such as the conjugate gradient method or GMRES.

With that in mind, try using the factorization in an iterative solver like my [ConjugateGradients.jl](https://github.com/mcovalt/ConjugateGradients.jl) package:

```julia
using Random
using SparseArrays
using LinearAlgebra
using ILUZero
using ConjugateGradients

Random.seed!(0)
n = 10
B = sprand(n,n,0.9)
cond(Matrix(B))
lu_factorization = ilu0(B)
r = rand(n)
x0, exit_code, num_iters = bicgstab((x,y) -> mul!(x,B,y), r; precon = (x,y) -> ldiv!(x,lu_factorization,y))
norm(B * x0 - r, Inf)
x1 = B \ r
norm(B * x1 - r, Inf)
norm(x0 - x1, Inf)
```

We get good solutions. To see the preconditioner at work, try again without using ILUZero.jl as a preconditioner:
```
x2, exit_code, num_iters = bicgstab((x,y) -> mul!(x,B,y), r)
```

You should see that it takes more iterations to achieve a similar result without the preconditioner.

I'm going to close this issue, but feel free to comment back if you have any questions or if I've totally missed the mark on my reply. This stuff is complicated and I wouldn't be surprised if that's the case!

**Comment by simon-lc** [comment]
Thanks for the detailed answer! this makes a lot of sense, thanks for the pointer I'll try combining it with ConjuguateGradients.jl
