### ISSUE TITLE
Extension for Incomplete Cholesky Decomposition

### ISSUE THREAD

**Issue by RoyiAvital** [mcovalt/ILUZero.jl#12]
Any chance to extend this to incomplete Cholesky decomposition?

In my [`C` implemetation](https://github.com/RoyiAvital/IncompleteCholeskyDecomposition) I also implemented the 𝜏 approach.
Any chance to have that as well?

**Comment by dpo** [comment]
[LimitedLDLFactorizations](https://github.com/JuliaSmoothOptimizers/LimitedLDLFactorizations.jl) already implements it.
