### ISSUE TITLE
Register this package?

### ISSUE THREAD

**Issue by amontoison** [mcovalt/ILUZero.jl#2]
It would be nice to register this package. We can do an ILU factorization with zero fill-in of any matrix type (Float32, Float64, Float128, BigFloat..). It's not the case with `ImcompleteLU` package.
It's a good preconditioner for iterative methods. I would like to use it in our package [Krylov.jl](https://github.com/JuliaSmoothOptimizers/Krylov.jl).

**Comment by mcovalt** [comment]
I haven't used Julia since before 1.0. With that said, I'd be happy to register this package after an evening of cleaning up the code, ensuring compatibility with the latest Julia, and making sure the docs are up to date.

**Comment by amontoison** [comment]
I tested your package with Julia 1.3 yesterday and it worked well!

**Comment by mcovalt** [comment]
https://github.com/JuliaRegistries/General/pull/23414

Package registration is _so_ slick with Julia these days. I'll close when that PR gets merged. Thanks for your patience!

**Comment by mcovalt** [comment]
https://github.com/JuliaRegistries/General/pull/23415

Looks like the package name was invalid. I changed the name.
