### ISSUE TITLE
README too pessimistic?

### ISSUE THREAD

**Issue by dpo** [mcovalt/ILUZero.jl#5]
I find this part of the README pessimistic to the point that it might turn users away:

> Why use ILUZero.jl? You probably shouldn't. Julia's built in factorization methods are much better.

The point of this package isn't to compete with (complete) factorization packages such as SuiteSparse. I feel the importance of LU(0) for preconditioning could be stressed instead.

**Comment by mcovalt** [comment]
Thanks for this suggestion!

I want to keep the recommendation focused solely on the software engineering aspects of the problem, not the mathematical properties ILU(0) itself. I updated the README.md to be less pessimistic in 36fdcae2440e9ea62648b674d40f332ea673f936.

Let me know if that could be improved. I'm open to suggestions. I'll close this issue if that looks good to you or if I don't hear back in, say, a month or so.

**Comment by dpo** [comment]
Looks good. Thanks!
